### ISSUE TITLE
How do we modify suggestions for playerID on the login page?

### ISSUE THREAD

**Issue by kepstein23** [empiricaly/empirica#107]
We'd like to suggest users input their MTurk ID on the initial screen where it says "This should be given to you. E.g. email, code..." but this appears to be hardcoded into empirica. How should we go about changing this text?

@JamesPHoughton

**Comment by npaton** [comment]
This should be fixed in the latest release. Run `empirica upgrade`.

Then you can customize the PlayerIDForm component in App.jsx (pseudo code):

```js
function PlayerIDForm({ onPlayerID }) {
   // ...
   const onSubmit = () =>   onPlayerID(id);
   // ...
}

// ...

          <GameFrame
            playerIDForm={PlayerIDForm}
            introSteps={[Introduction]}
            exitSteps={[ExitSurvey]}
          >
              ...
          </GameFrame>
```

You can take the example of the PlayerID form in core here: https://github.com/empiricaly/empirica/blob/main/lib/%40empirica/player/src/components/PlayerID.tsx
