### ISSUE TITLE
batch level ready/error flag

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#127]
We're currently using the `onNewBatch` callback to fetch all of the resources that will be needed to run the games in the batch. If the fetch fails, we currently log errors to the server console, but there is no warning in the admin interface. It would be nice to have a status flag for batches that would be set at the end of the `onNewBatch` callback, and which says that the batch is ready to start. If there is an error, and the ready flag is not set, we shouldn't be able to start the batch.

**Comment by npaton** [comment]
The API for tracking new batches has changed. Either way, there's currently no concept of a failed batch creation. Nor is there such a concept for game, player, round, or stage creation. They always succeed as far as Empirica is concerned (outside of bugs...) There are many callbacks we could consider to be affecting the status of the core objects (e.g.: on status change, on player assignment, etc.). In my opinion, it would be hard to say which callback should throw objects into a new "failed" state and what to do with this new state in all scenarios.

I feel like this is beyond the scope of the core at this time. This should be handled in individual experiments since it is an overly specific behavior.

In this case, one possible solution would be to wrap your setup in a try/catch block and then set a key on the batch with the outcome of the setup. Then have a custom assignment where you can check this flag to see which batch is "successful" and only assign to those. This might be too complicated. I'd imagine this initialization should work in the vast majority of cases. Maybe just log it, and when you create batches, just check the logs for a few seconds after the batch creation to see if it worked and if it didn't, cancel it manually.

If a clear solution for what to do with initialization errors appears that considers all the intricacies of such a problem, which would not make everything more complicated for a relatively small percentage of usage, I'd be glad to reconsider this. For now, I will close this issue.

**Comment by npaton** [comment]
It just came to mind, there might be a solution for this already... You can add the try/catch, and in case of an error, there is a `batch.end(reason)` API you should have access to in the callback. So you can just cancel the batch right then and there. Unfortunately, at the moment, you can only mark it as "ended" and not "failed" or "terminated" (aka canceled).

Note that this API has not been tested in this context, so please let us know if it works as expected.

**Comment by JamesPHoughton** [comment]
That looks like the right solution - for the experimenter to write the try-catch and run batch.end() if necessary. We can console log that the batch creation failed, and that'll be a good diagnostic.
