### ISSUE TITLE
player.set("key", 0) seems to set "key"==null

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have the following code in an `onGameStart` callback, inside a loop over all players:
```js
  Empirica.on("game", "start", async (ctx, { game, start }) => {
    if (!start) return;

    const { players } = game;
    for (const player of players) {
      player.set("testn1", -1);
      player.set("test0", 0);
      player.set("test1", 1);
      player.set("testempty", "");
      console.log("testn1", player.get("testn1"));
      console.log("test0", player.get("test0"));
      console.log("test1", player.get("test1"));
      console.log("testempty", player.get("testempty"));
    }
...
```

Here's what I get in the log:
```bash
[server] testn1 -1
[server] test0 null
[server] test1 1
[server] testempty null
[server] testn1 -1
[server] test0 null
[server] test1 1
[server] testempty null
}
```

For some reason, the 0 value and empty string are getting converted to null. In the tajriba.json:
```json
{"kind":"Attribute","obj":{"id":"01H09G98H7N2Z8JFXJ0AMQ8X6Z","createdAt":"2023-05-12T22:50:50.791945-04:00","createdByID":"01H09G8BZMX4JH0R1JBPFTXVPT","key":"testn1","val":"-1","nodeID":"01H09G8XG0DJ58FVX5JW5E0NCJ"}}
{"kind":"Attribute","obj":{"id":"01H09G98H7N2Z8JFXJ0B9NHVAT","createdAt":"2023-05-12T22:50:50.791945-04:00","createdByID":"01H09G8BZMX4JH0R1JBPFTXVPT","key":"test0","val":"null","nodeID":"01H09G8XG0DJ58FVX5JW5E0NCJ"}}
{"kind":"Attribute","obj":{"id":"01H09G98H7N2Z8JFXJ0EV5948A","createdAt":"2023-05-12T22:50:50.791945-04:00","createdByID":"01H09G8BZMX4JH0R1JBPFTXVPT","key":"test1","val":"1","nodeID":"01H09G8XG0DJ58FVX5JW5E0NCJ"}}
{"kind":"Attribute","obj":{"id":"01H09G98H7N2Z8JFXJ0FD0KQE3","createdAt":"2023-05-12T22:50:50.791945-04:00","createdByID":"01H09G8BZMX4JH0R1JBPFTXVPT","key":"testempty","val":"null","nodeID":"01H09G8XG0DJ58FVX5JW5E0NCJ"}}
{"kind":"Attribute","obj":{"id":"01H09G98H7N2Z8JFXJ0FKMV7H3","createdAt":"2023-05-12T22:50:50.791945-04:00","createdByID":"01H09G8BZMX4JH0R1JBPFTXVPT","key":"roundIndex","val":"null","nodeID":"01H09G98FZT60MK4JQSG02ZTPY"}}
```

I've also seen this behavior where `stage.get("index")` returns null for the first stage.

Unfortunately, Its not easily reproducible. if I put the same code in a dummy project, I get what I expect for both the zero and empty string condition.
```
[server] testn1 -1
[server] test0 0
[server] test1 1
[server] testempty 
[server] testn1 -1
[server] test0 0
[server] test1 1
[server] testempty 
```

### Steps To Reproduce

I'm having trouble making a minimal example, as this is clearly interacting with something else in my code - I just can't tell what.

### Empirica Version

```text
Version: v1.3.1
SHA:     bce7ea3
Branch:  main
Time:    2023-04-30T08:37:49Z

Client:  1.3.1
Server:  1.3.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JamesPHoughton** [comment]
This may be a problem with a falsy value getting a null default, instead of proper nullish coalescing?

**Comment by npaton** [comment]
Yeah. It's a falsy value problem, looks like. But it doesn't make much sense. Looking at the path of the code in `.set()`, there is no reason to be using the falseness instead of the actual value. We never try to cast it in any way.

And I cannot reproduce it. It's very hard to work on without a reproducible case. Do you have a minimal reproduction yet? Otherwise if you can send me a link to the project where it's happening.

**Comment by npaton** [comment]
I have not been able to reproduce this yet. But I will take a closer look toward end of week. If you have reproducible case, a repo you can share, that would be helpful. Thanks!

**Comment by milenavt** [comment]
Hi Nicolas, here is a [link](https://github.com/social-research/redistribution) and some notes:
- Main issue: `0` and  `false` appear to be set to attributes as `null`
- Try a 2-player game - the slider reads values from `player.round.vote` and works for all values `1-100` but not `0` (reads as `null`) 
- Relatedly, note in `tajriba.json` that `round.displayResult` in first round is saved as `null` instead of `false` and `player.round.vote` and `player.bonus` are saved as `null` instead of `0`
- I am running this on macOS Monterey 12.6.2

**Comment by npaton** [comment]
I've finally found the issue, sorry for the delay. I've found another unrelated issue where older versions of the installer could cause problems. Please run the installer again then upgrade:

```sh
curl https://get.empirica.dev | sh
empirica upgrade --global
```

Let me know how it goes.

**Comment by milenavt** [comment]
Perfect, it works as expected now. Many thanks!
