### ISSUE TITLE
flag to stop server restart on failure to help with debugging during development

### ISSUE THREAD

**Issue by JamesPHoughton** [empiricaly/empirica#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

During development, if the server throws an error, it will likely restart the server, and then retry everything and re-throw the same error, in a loop. That means you have to `<ctrl>-c` real quick and then scroll up to find the bug. 

### Describe the solution you'd like

It would be helpful to be able to tell the server to just quit on a failure and display the debugging information. The flag could be something like `--restartOnError false`, with default behavior being true.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by npaton** [comment]
I feel like the default behavior should be that the server should not try to restart if crashes, until code changes are made. Does that make sense?

**Comment by npaton** [comment]
In the latest release, there have been some improvements added. One of the improvements is in the server template: https://github.com/empiricaly/empirica/blob/main/internal/templates/source/callbacks/src/index.js#L38-L41 This is necessary to catch unhandledRejections. Otherwise, the server does attempt to restart a couple of times and then gives up if the exceptions happen quickly. Also more errors should be logged.
