### ISSUE TITLE
useX does not load data between consent and intro steps

### ISSUE THREAD

**Issue by npaton** [empiricaly/empirica#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

> Any insights in why variables may be undefined before refresh when switching from consent to intro steps?

### Steps To Reproduce

1. Use useGame in intro step
2. Accept consent
3. useGame remains null
4. refresh browser
5. userGame returns Game

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by malsobay** [comment]
I'm facing what I think is a related issue, but with a slightly different flow: 
1. Show consent, player submits and moves onto intro steps 
2. Page does not load, because `game` is not defined, causing an error 
3. Refresh page, everything works as expected 

This is happening consistently on any new game.

**Comment by npaton** [comment]
These should be fixed in the latest (1.4.2).
