### ISSUE TITLE
playerRounds data not saving

### ISSUE THREAD

**Issue by aliciamchen** [empiricaly/empirica#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The data I wanted to save in playerRounds is empty in the csv when I do `empirica export`. This has not happened to me with previous versions of empirica, with the same experiment code. 

The data does log to the console (e.g. when I call `player.round.get("attribute")` in callbacks), and also doesn't prevent the experiment from progressing (I need to access this information for the game to continue);  it just doesn't show up in the csv. 

### Empirica Version

```text
Version: v1.8.11
SHA:     fce31f9
Build:   154
Branch:  main
Time:    2023-12-20T10:26:18Z
```

### What OS are you seeing the problem on?

macOS

### What browser are you seeing the problem on?

Does not apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aliciamchen** [comment]
I think what is happening here is that within a round it's saving the first value of the attribute, but as its value updates through the stages within the round, it doesn't write that value (but what I want is it to write the last value, at the end of the round / after all the stages)

**Comment by npaton** [comment]
I believe this should be fixed in the latest release. It managed to reproduce a case where data update "un place" would not save. I think this is what you're seeing, but I'm not 100% sure, since I don't know exactly where you're changing this data. Here are the release notes explaining this in further detail: https://github.com/empiricaly/empirica/releases/tag/%40empirica%2Fcore%401.8.12

Let me know if this makes sense, or if you can point me to where the data is updated in your code, and I can confirm this is the problem. Thanks!

**Comment by aliciamchen** [comment]
Thank you! I'll try it again

**Comment by aliciamchen** [comment]
This is fixed, thank you!
