### ISSUE TITLE
Unhandled error in `Tajriba.emit`

### ISSUE THREAD

**Issue by frasalvi** [empiricaly/empirica#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have caught a bunch of `Error: Unhandled error. (undefined)` from `Tajriba.emit(assets/index)` on the client side, thanks to Sentry. There are no relevant logs on the server side, and the error seems to be non-breaking so far: the users' pages just go white for a few seconds, and then get restored as normal. 

### Empirica Version

```text
Version: v1.9.0
SHA:     6dc8adb
Build:   166
Branch:  main
Time:    2024-01-01T08:11:38Z
```

### What OS are you seeing the problem on?

Windows

### What browser are you seeing the problem on?

Chrome

### Relevant log output

```shell
[from Sentry]

thrown at /assets/index.df48a287.js in Tajriba.emit at line 39039:15

    if (args.length > 0)
      er = args[0];
    if (er instanceof Error) {
      throw er;
    }
    var err = new Error(
      "Unhandled error." + (er ? " (" + er.message + ")" : "")
    );
    err.context = er;
    throw err;
  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frasalvi** [comment]
Attaching also the Raw trace from Sentry:
```
Error: Unhandled error. (undefined)
  at Tajriba.emit(/assets/index.df48a287.js:39039:15)
  at error(/assets/index.df48a287.js:39469:16)
  at Object.emit(/assets/index.df48a287.js:30885:11)
  at socket2.onerror(/assets/index.df48a287.js:30938:42)
```

**Comment by npaton** [comment]
This appears to be linked to a connection error (disconnection). The player should recover automatically from this. There is nothing we can do about disconnections, it can just happen, for whatever reason. The system will just try to reconnect. In the next update, I have added an intercept for the disconnection and it won't throw this cryptic error anymore, but the behavior should otherwise be the same.
