### ISSUE TITLE
missing `startedAt` for player.stage and player.round

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#49]
At the moment, both the `player.stage` and `player.round` have two timestamps: 
* `createdAt` : which is created at the initialization of the game.
* `updatedAt`: which can be seen as when the stage/round for that player has ended. 

But this is missing `startedAt` which is the time that this stage/round started for this particular player. this is crucial for computing the duration it took for the player to finish a stage/round.

**Comment by npaton** [comment]
The start time of each stage is in the stage object, in the `startTimeAt` field. The start time is the same for all players, it is not duplicated into each playerStage object. We could work on making it accessible through the playerStage (`player.stage`) as a proxy to the value on stage.

**Comment by amaatouq** [comment]
Aha I see .. and the `startTimeAt` is the time that stage started, not the time of initialization (i.e. when we insert the records before the game starts)

**Comment by npaton** [comment]
Yes, `createdAt` and `updatedAt` are on every single record in the DB, they are there for things like sorting lists by last created/updated (say batches in the admin UI), and debugging. They are not always explicitly used in the app and are unrelated to "business logic" (running experiments), but I always add them because they always come in handy, and it makes sense to track these things. ;)

**Comment by amaatouq** [comment]
I think everything should have a `duration` field. `game.duration` from the lobby to the exit survey, `round.duration` the sum of the duration of all stages, `stage.duration`, which is how long the stage actually took (whether advanced automatically or everyone submitted. this is related to #17
