### ISSUE TITLE
missing `submittedAt` for some player_stages

### ISSUE THREAD

**Issue by amaatouq** [empiricaly/empirica#50]
Some `player.stages` are missing `submittedAt`. is the field `submittedAt` only exits if `player.stage.submit();` is invoked? otherwise, it doesn't? (i.e., if the stage ends due to timeout). 

I think we should always have `submittedAt` and then have another attribute `submitMethod` that can indicate whether it was `userSubmitted` or `stageTimedOut` .. I am sure better names for the key/value can be found.

**Comment by npaton** [comment]
Yes, submittedAt is only set if the users explicitly submitted. Otherwise, the stage ends with a timeout, and the end time is: `stage.startTimeAt + stage.durationInSeconds`. We could have a couple helper methods to help people with this. We could have similar type helpers as are discussed in #48   (wouldn't be in the DB, calculated):
* `player.stage.endTimeAt` which give the absolute end time of the stage for that player, whether they submitted or it timed out.
* `player.stage.durationInSeconds` which give the duration of the stage for that player, whether they submitted or it timed out.

While we're at it, we could also add helpers for round and game duration, and start end times.

I really want to do an overhaul of the `player.stage`, `player.round`, `player.game` objects, to make them more lazily initialized, and to make it more easy to add nice helpers like this.

We can add these to help make the API more friendly, but note that already, all these values can be calculated with the information provided. Let me know if any of them aren't clear.

**Comment by amaatouq** [comment]
it is not about the ability to calculate them in the game. It for analysis. These numbers will be calculated in the analysis of most experiments, so we might as well make them handly available. Maybe no in the DB, but for the export function. things like round duration, stage duration, game duration, whether the player submitted or it was timed out.

**Comment by npaton** [comment]
I propose we create a new ticket with all the new field demands, for in game and for export. Or we can just rename one of these last 2 tickets and list everything in here, whichever is most convenient.

**Comment by amaatouq** [comment]
yes, let's do that

**Comment by amaatouq** [comment]
this is now related to #17 which would solve this one too
